export default {
  GET_ALL_NOTE: "GET_ALL_NOTE",
  GET_NOTE_BY_ID: "GET_NOTE_BY_ID",
  GET_ALL_DELETED_NOTE: "GET_ALL_DELETED_NOTE",
  GET_ALL_FAVOURITE_NOTE: "GET_ALL_FAVOURITE_NOTE",
  GET_PUBLIC_NOTE: "GET_PUBLIC_NOTE",
};